### ISSUE TITLE
Old A record

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy.github.io#9]
The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain.

Since it's using apex, there are A-RECORDS setup with the DNS provider and the IP numbers need to be updated

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

@rafalkasa

**Comment by rafalkasa** [comment]
Fix A-RECORDS for the schemaspy.org and install ssl certificate, currently domain is available based on https:// with Enforce policy
